#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

PROG=/usr/bin/mihomo
CONF_DIR=/etc/mihomo

start_service() {
    [ -x "$PROG" ] || {
        echo "Error: $PROG not executable or missing"
        return 1
    }
    [ -d "$CONF_DIR" ] || mkdir -p "$CONF_DIR"

    procd_open_instance mihomo
    procd_set_param command "$PROG" -d "$CONF_DIR"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    procd_send_signal mihomo
}
